Pin cmake 3.22.3
pytorch/builder pull request #1011
Opened 2022-03-31 16:52 UTC by zengk95

Addresses #1010

Searched for all usages of `install.*cmake`

2022-03-31 17:40 UTC, malfet approved these changes

2022-03-31 17:46 UTC, malfet requested changes
Do not pin version in `apt-get`/`yum install` command, as cmake=3.23 is not available there yet (which is probably reflected in CI failures)

2022-03-31 17:46 UTC, malfet commented on manywheel/Dockerfile
> +RUN yum install -y cmake3-3.22.3 && \
Same as above
```suggestion
RUN yum install -y cmake3 && \
```

2022-03-31 17:46 UTC, malfet commented on libtorch/Dockerfile
> +RUN /opt/conda/bin/conda install -y cmake=3.22.3
Let's stick with 3.14 as it allows us to validate that CMakeFile is correct at minspec
```suggestion
RUN /opt/conda/bin/conda install -y cmake=3.14
```

2022-03-31 17:46 UTC, malfet commented on manywheel/conda_build.sh
> +yum install -y wget git cmake-3.22.3
```suggestion
yum install -y wget git cmake
```

2022-04-05 15:13 UTC, zengk95 commented
@malfet I removed those pins as suggested. Could you review again?

2022-04-05 16:18 UTC, malfet approved these changes
Thank you for the updates, looks good to me

2022-04-05 16:18 UTC, merged

2022-04-06 17:25 UTC, malfet commented
Looks like it caused MacOS night jobs to fail, as cmake-3.22.3 is not available from Anaconda, is it: https://anaconda.org/anaconda/cmake