[WIP] Add support for VS2022 Windows build.
pytorch/builder pull request #1187
Opened 2022-11-07 12:06 UTC by Blackhex

2022-11-07 12:07 UTC, Blackhex commented
@pytorchbot label ciflow/trunk

2022-11-07 12:22 UTC, Blackhex commented
This is still WIP, I just need an advice on how to run pipelines with the changes.

2022-11-07 12:25 UTC, Blackhex commented on conda/build_pytorch.sh
> +        vs_package="vs$VS_YEAR"
I am not sure about this. There is/was a discrepancy between `VS_YEAR` and `VC_YEAR` variable naming. From Conda standpoint, `VC_YEAR` does not exists vile `VS_YEAR` does (https://docs.conda.io/projects/conda-build/en/stable/user-guide/environment-variables.html).

2022-11-07 12:25 UTC, Blackhex commented on conda/build_vision.sh
> +    time conda build -c $ANACONDA_USER --no-anaconda-upload vs2022
This needs to be tested somehow?

2022-11-07 12:31 UTC, Blackhex commented on windows/cuda116.bat
> +set CMAKE_GENERATOR=Visual Studio 17 2022 Win64
I've updated only CUDA 11.6 and 11.7 as those are listed in the build selection table on the homepage (https://pytorch.org/)

2022-11-07 22:28 UTC, Blackhex commented on windows/internal/vs2022_install.ps1
> +$VS_DOWNLOAD_LINK = "https://ossci-windows.s3.us-east-1.amazonaws.com/vs17.3.6_BuildTools.exe"
The file currently does not exist, how to get it there?

2022-11-08 18:36 UTC, malfet requested changes
We should not add any new batch files as there are no way to abort script execution on error, which makes debugging any failures much harder. Please rewrite them either into PowerShell or better into Python

2022-11-08 18:42 UTC, Blackhex commented
@malfet Sure, no problem, but please note that I currently don't have permissions to run PR pipelines on this repo.

2023-05-17 07:05 UTC, closed without merging