Copy mkl windows
pytorch/builder pull request #1467
Opened 2023-08-04 05:31 UTC by mantaionut

2023-10-23 19:48 UTC, malfet requested changes

2023-10-23 19:48 UTC, malfet commented on conda/pytorch-nightly/meta.yaml
> +    - mkl==2021.4.0 # [win]
This needs to be moved under if not defined cross compiling, isn't it?

2023-10-23 19:48 UTC, malfet commented on conda/pytorch-nightly/meta.yaml
> +    - mkl-devel=2021.4.0 # [win]
Condition should be x86_64 and win

2023-10-23 19:48 UTC, malfet commented on conda/pytorch-nightly/meta.yaml
> +    - mkl==2021.4 # [x86_64]
No, one could not make this change, please limit it to not win

2023-11-29 09:40 UTC, mantaionut commented
@malfet I have made the requested changes. Can you please recheck the changes?

2023-12-07 17:29 UTC, kit1980 commented
@mantaionut please resolve merge conflicts

2023-12-08 05:06 UTC, malfet reviewed
Looks ok, but can we have a test plan of sorts (for example by creating PR against PyTorch and running binary builds?)

2023-12-08 05:38 UTC, malfet approved these changes
Thank you for making the change, please resolve merge conflicts, otherwise LGTM

2023-12-22 19:29 UTC, mantaionut commented
@malfet I rebased and fix the conflicts. However due to the current python 3.12 conda build which is using mkl=2023.1 I was not able to compile it with mkl 2021.4.0 due to conda conflicts. So I made the change to use mkl 2023.1 on conda py12 while on all the other specifications it remains with mkl 2021.4.0.

2024-01-22 17:48 UTC, merged