Avoid finding out std::basic_string_view
pytorch/builder pull request #1528
Opened 2023-09-11 06:24 UTC by cyyever

With pytorch moving to C++17, change the pattern to avoid finding out std::basic_string_view

2023-12-18 09:36 UTC, cyyever commented
@huydhn Can help review？

2023-12-26 02:17 UTC, huydhn approved these changes

2023-12-26 18:27 UTC, malfet requested changes
Hmm, move to C++17 should not in any way affect what symbols we expect to see, should it?

2023-12-27 08:14 UTC, cyyever commented
@malfet Unfortunately, it uses substring match to find PRE_CXX11_SYMBOLS, however, std::string_view was falsely recognised as PRE_CXX11_SYMBOLS, preventing adoption of std::string_view.

2023-12-27 15:34 UTC, malfet approved these changes

2023-12-27 15:35 UTC, merged

2023-12-27 15:35 UTC, malfet commented
@cyyever thank you for the explanation, merged.