Xu win mkl static
pytorch/builder pull request #1798
Opened 2024-04-24 16:10 UTC by xuhancn

2024-04-24 16:16 UTC, malfet requested changes
Please create a test PR against PyTorch/PyTorch

2024-04-24 20:09 UTC, xuhancn commented
Triggerred test from the dummy PR: https://github.com/pytorch/pytorch/pull/124853
From the result: https://github.com/pytorch/pytorch/actions/runs/8821164940/job/24216482475, I still do some work to enable mkl-static for pytorch Windows: https://github.com/pytorch/pytorch/issues/124869

2024-04-25 15:40 UTC, xuhancn commented
> Triggerred test from the dummy PR: [pytorch/pytorch#124853](https://github.com/pytorch/pytorch/pull/124853) From the result: https://github.com/pytorch/pytorch/actions/runs/8821164940/job/24216482475, I still do some work to enable mkl-static for pytorch Windows: [pytorch/pytorch#124869](https://github.com/pytorch/pytorch/issues/124869)

After https://github.com/pytorch/pytorch/pull/124925 merged, the static mkl not support issue is gone.
Test job: https://github.com/pytorch/pytorch/actions/runs/8834373375/job/24255862902?pr=124853
<img width="797" alt="image" src="https://github.com/pytorch/builder/assets/8433590/30aa1b55-a3ad-4674-b577-9be21c4fbdd5">

2024-04-25 17:31 UTC, xuhancn commented
Final test: https://github.com/pytorch/pytorch/pull/124853
Windows wheel test: 
Windows libtorch release: https://github.com/pytorch/pytorch/actions/runs/8836876609/job/24264460568 
Windows libtorch debug: https://github.com/pytorch/pytorch/actions/runs/8836876732/job/24264451618

2024-04-25 17:47 UTC, malfet approved these changes

2024-04-25 21:41 UTC, xuhancn commented
> Final test: [pytorch/pytorch#124853](https://github.com/pytorch/pytorch/pull/124853) Windows wheel test: https://github.com/pytorch/pytorch/actions/runs/8836875904/job/24264643410 Windows libtorch release: https://github.com/pytorch/pytorch/actions/runs/8836876609/job/24264460568 Windows libtorch debug: https://github.com/pytorch/pytorch/actions/runs/8836876732/job/24264451618

@malfet All test passed.

2024-04-26 13:20 UTC, merged

2024-06-11 21:39 UTC, atalman commented
I am getting an error with latest Windows AMI:
```
-- Checking for [blis]
--   Library blis: BLAS_blis_LIBRARY-NOTFOUND
-- Checking for [Accelerate]
--   Library Accelerate: BLAS_Accelerate_LIBRARY-NOTFOUND
-- Checking for [vecLib]
--   Library vecLib: BLAS_vecLib_LIBRARY-NOTFOUND
-- Checking for [flexiblas]
--   Library flexiblas: BLAS_flexiblas_LIBRARY-NOTFOUND
-- Checking for [openblas]
--   Library openblas: BLAS_openblas_LIBRARY-NOTFOUND
-- Checking for [openblas - pthread - m]
--   Library openblas: BLAS_openblas_LIBRARY-NOTFOUND
-- Checking for [openblas - pthread - m - gomp]
--   Library openblas: BLAS_openblas_LIBRARY-NOTFOUND
-- Checking for [libopenblas]
--   Library libopenblas: BLAS_libopenblas_LIBRARY-NOTFOUND
-- Checking for [goto2 - gfortran]
--   Library goto2: BLAS_goto2_LIBRARY-NOTFOUND
-- Checking for [goto2 - gfortran - pthread]
--   Library goto2: BLAS_goto2_LIBRARY-NOTFOUND
-- Checking for [acml - gfortran]
--   Library acml: BLAS_acml_LIBRARY-NOTFOUND
-- Checking for [blis]
--   Library blis: BLAS_blis_LIBRARY-NOTFOUND
-- Could NOT find Atlas (missing: Atlas_CBLAS_INCLUDE_DIR Atlas_CLAPACK_INCLUDE_DIR Atlas_CBLAS_LIBRARY Atlas_BLAS_LIBRARY Atlas_LAPACK_LIBRARY) 
-- Checking for [ptf77blas - atlas - gfortran]
--   Library ptf77blas: BLAS_ptf77blas_LIBRARY-NOTFOUND
```
and finaly failing:
```
2024-06-11T16:40:56.0998121Z UfuncCUDA_add.cu
2024-06-11T16:44:04.9996771Z tmpxft_00000284_00000000-7_UfuncCUDA_add.compute_90.cudafe1.cpp
2024-06-11T16:44:04.9997305Z 
2024-06-11T16:44:04.9998101Z [8312/8413] Building CUDA object caffe2\CMakeFiles\torch_cuda.dir\__\aten\src\ATen\native\cuda\Unique.cu.obj
2024-06-11T16:44:04.9999192Z Unique.cu
2024-06-11T16:44:04.9999334Z 
2024-06-11T16:44:04.9999562Z tmpxft_00000ef4_00000000-7_Unique.compute_90.cudafe1.cpp
2024-06-11T16:44:04.9999918Z 
2024-06-11T16:44:05.0000129Z [8313/8413] Linking CXX shared library bin\torch_cuda.dll
2024-06-11T16:44:05.0000668Z FAILED: bin/torch_cuda.dll lib/torch_cuda.lib 
2024-06-11T16:44:05.0005278Z cmd.exe /C "cd . && C:\actions-runner\_work\pytorch-canary\pytorch-canary\builder\windows\conda\envs\py38\Library\bin\cmake.exe -E vs_link_dll --intdir=caffe2\CMakeFiles\torch_cuda.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\BUILDT~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\torch_cuda.rsp  /out:bin\torch_cuda.dll /implib:lib\torch_cuda.lib /pdb:bin\torch_cuda.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /ignore:4099 /INCREMENTAL:NO  && cd ."
2024-06-11T16:44:05.0059710Z LINK: command "C:\PROGRA~2\MICROS~1\2019\BUILDT~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\torch_cuda.rsp /out:bin\torch_cuda.dll /implib:lib\torch_cuda.lib /pdb:bin\torch_cuda.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /ignore:4099 /INCREMENTAL:NO /MANIFEST /MANIFESTFILE:bin\torch_cuda.dll.manifest" failed (exit code 1181) with the following output:
2024-06-11T16:44:05.0062298Z LINK : fatal error LNK1181: cannot open input file 'NOTFOUND.lib'
2024-06-11T16:44:05.0062728Z 
2024-06-11T16:44:05.0062875Z ninja: build stopped: subcommand failed.
```